#spring.cloud.config.enabled: true
#spring.cloud.config.discovery.enabled: true
#eureka.instance.preferIpAddress: false
#eureka.client.registerWithEureka: true
#eureka.fetchRegistry: true
#eureka.serviceUrl.defaultZone: http://localhost:8761/eureka/


spring.jpa.database: "MYSQL"
spring.datasource.platform: "mysql"
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://localhost:3306/hrDB"
spring.datasource.username: "root"
spring.datasource.password: "Mysql_123"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"
server.port: 8096

multipart.max-file-size: 100MB
multipart.max-request-size: 100MB
